# Generated by Django 4.2.2 on 2023-06-22 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_rename_marcaproducto_producto_peso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('idTipoPago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True, unique=True)),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idVenta', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.CharField(default='', max_length=999999)),
                ('tipoPago', models.ForeignKey(blank=True, db_column='idTipoPago', null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.marca')),
            ],
        ),
    ]
