# Generated by Django 4.2.2 on 2023-06-22 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_formapago_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='tipoPago',
            field=models.ForeignKey(blank=True, db_column='idTipoPago', null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.formapago'),
        ),
    ]
