# Generated by Django 4.2.2 on 2023-06-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_alter_venta_tipopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='nombre',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
