# Generated by Django 4.2.2 on 2023-06-22 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_venta_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='nombre',
            new_name='nombreVenta',
        ),
        migrations.AddField(
            model_name='venta',
            name='idProducto',
            field=models.ForeignKey(blank=True, db_column='idProducto', null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.producto'),
        ),
    ]
