# Generated by Django 4.2.2 on 2023-06-22 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_rename_nombre_venta_nombreventa_venta_idproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliado',
            fields=[
                ('idAfiliado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True, unique=True)),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='nivelEstudio',
            fields=[
                ('idNivel', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True, unique=True)),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idRegion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True, unique=True)),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='tipoUsuario',
            fields=[
                ('idTipoUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True, unique=True)),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.IntegerField(unique=True)),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('fechaNacimiento', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField()),
                ('nivelDeEstudio', models.ForeignKey(blank=True, db_column='idNivel', null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.nivelestudio')),
                ('region', models.ForeignKey(blank=True, db_column='idRegion', null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.region')),
                ('tipoUsuario', models.ForeignKey(blank=True, db_column='idTipoUsuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.tipousuario')),
            ],
        ),
    ]
