# Generated by Django 4.2.2 on 2023-06-22 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_afiliado_nivelestudio_region_tipousuario_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipoproducto',
            old_name='idtTipoproducto',
            new_name='idTipoproducto',
        ),
    ]
